---
title: "IE, clase 1"
author: "ricardo mayer"
date: "8/12/2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Variables Aleatorias

- Esta clase: Cap 5 de A&S 2008
- Qué es una variable aleatoria
- Variable aleatoria continua
- Variable aleatoria discreta



## Valor esperado y varianza

- Valor esperado
- Varianza
- Desviación estándar o típica
- Manual, Excel-manual, R-manual


## Distribución de probabilidad binomial

- Distribución Binomial y Bernoulli
- Experimento Binomial:
    + El experimento consiste en una serie de n ensayos idénticos.
    + En cada ensayo hay dos resultados posibles. A uno de estos resultados se le llama
éxito y al otro se le llama fracaso.
    + La probabilidad de éxito, que se denota *p*, no cambia de un ensayo a otro. Por ende,
la probabilidad de fracaso, que se denota *1-p*, tampoco cambia de un ensayo a
otro.
    + Los ensayos son independientes.
- Si la variable Bernoulli toma valores 1 (éxito) y 0 (fracaso) ... **cuál su valor esperado? y su varianza?**